- name: Ensure that zsh is installed
  aur:
    name:
      - zsh

- name: Change shell to zsh
  become: yes
  command: chsh -s /bin/zsh "{{host_username}}"

- name: Set up zgen folder
  git:
    repo: https://github.com/tarjoilija/zgen.git
    dest: ~/.zgen