#!/usr/bin/env ansible-playbook
---
- name: Apply Arch configuration to local machine
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Get my username
      local_action: command whoami
      register: host_username
      become: no
  
    - set_fact:
        host_username: "{{host_username.stdout}}"

    - name: Update package cache
      pacman:
        update_cache: yes
      become: yes
      
  roles:
    - nvidia
    - enpass
    - dconf
    - shell
    - dotfiles
    - julia
    - misc-software

