- name: Ensure that adapta theme is available
  aur:
    name: gtk-theme-adapta

# /org/gnome/desktop/background/
- name: Set background
  dconf:
    key: /org/gnome/desktop/background/{{item.key}}
    value: "{{item.value}}"
  with_dict: 
    picture-options: "'zoom'"
    picture-uri: "'file:///usr/share/backgrounds/gnome/Icescape.jpg'"

# /org/gnome/desktop/input-sources/
- name: Set input sources
  dconf: 
    key: /org/gnome/desktop/input-sources/{{item.key}}
    value: "{{item.value}}"
  with_dict:
    sources: "[('xkb', 'us'), ('xkb', 'mao')]"
    xkb-options: "['caps:swapescape']"
    
# /org/gnome/desktop/interface/
- name: Set desktop interface options
  dconf:
    key: /org/gnome/desktop/interface/{{item.key}}
    value: "{{item.value}}"
  with_dict:
    clock-show-seconds: "true"
    clock-show-weekday: "true"
    gtk-theme: "'Adapta'"
    show-battery-percentage: "true"

# /org/gnome/desktop/privacy/
- name: Set desktop privacy options
  dconf:
    key: /org/gnome/desktop/privacy/{{item.key}}
    value: "{{item.value}}"
  with_dict:
    remove-old-temp-files: "true"
    remove-old-trash-files: "true"

# /org/gnome/desktop/screensaver/
- name: Enable screen lock
  dconf:
    key: "/org/gnome/desktop/screensaver/lock-enabled"
    value: "true"

# /org/gnome/desktop/session/
- name: Enable screen lock after 5 mins
  dconf:
    key: "/org/gnome/desktop/session/idle-delay"
    value: "uint32 300"

# /org/gnome/nautilus/preferences/
- name: Set list view as default in Nautilus
  dconf:
    key: "/org/gnome/nautilus/preferences/default-folder-viewer"
    value: "'list-view'"

# /org/gnome/settings-daemon/plugins/color/
- name: Set Night Light options
  dconf:
    key: /org/gnome/settings-daemon/plugins/color/{{item.key}}
    value: "{{item.value}}"
  with_dict:
    night-light-enabled: "true"
    night-light-schedule-automatic: "false"
    night-light-schedule-from: "21.0"
    night-light-schedule-to: "6.0"
    night-light-temperature: "uint32 3000"
    
# /org/gnome/settings-daemon/plugins/xsettings/
- name: Increase font hinting so that underscores show up in terminal
  dconf:
    key: "/org/gnome/settings-daemon/plugins/xsettings/hinting"
    value: "'none'"
    
# /org/gnome/shell/
- name: Set favourite apps for dock
  dconf: 
    key: "/org/gnome/shell/favorite-apps"
    value: "['org.gnome.Nautilus.desktop', 'firefox.desktop', 'visual-studio-code.desktop']"

# /org/gnome/shell/extensions/dash-to-dock/
- name: Set dock options
  dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/{{item.key}}
    value: "{{item.value}}"
  with_dict:
    dash-max-icon-size: "64"
    intellihide-mode: "'ALL_WINDOWS'"

# /org/gnome/shell/extensions/user-theme/
- name: Set gnome-shell theme
  dconf:
    key: "/org/gnome/shell/extensions/user-theme/name"
    value: "'Adapta'"
    
# /org/gnome/system/location/
- name: Disable location awareness
  dconf: 
    key: "/org/gnome/system/location/enabled"
    value: "false"
    
# /org/gtk/settings/file-chooser/
- name: Set dock options
  dconf:
    key: /org/gtk/settings/file-chooser/{{item.key}}
    value: "{{item.value}}"
  with_dict:
    show-hidden: "true"
    sort-directories-first: "true"
