# Paths to all custom keybindings
- name: Custom keybindings
  dconf: 
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"

# Terminal shortcut
- name: Terminal shortcut (custom0)
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
    value: "'<Super>t'"

- name: Terminal shortcut (custom0) command
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
    value: "'gnome-terminal'"

- name: Terminal shortcut (custom0) name
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
    value: "'Launch terminal'"

# Enpass assistant
- name: Enpass assistant shortcut (custom1)
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding"
    value: "'<Primary><Alt>slash'"

- name: Enpass assistant shortcut (custom1) command
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command"
    value: "'/opt/enpass/Enpass showassistant'"

- name: Enpass assistant shortcut (custom1) name
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name"
    value: "'Show Enpass assistant'"
