- name: Ensure chezmoi is installed before this step
  aur:
    name: chezmoi-bin

- name: Ensure chezmoi config directory exists
  file:
    path: ~/.config/chezmoi
    state: directory
    recurse: yes

- name: Create chezmoi data file (can later be modified manually)
  copy:
    src: chezmoi.toml
    dest: ~/.config/chezmoi/chezmoi.toml
    force: no

- name: Get chezmoi directory
  git:
    repo: ssh://git@github.com/swt30/dotfiles.git
    dest: ~/.local/share/chezmoi
    accept_hostkey: yes

- name: Apply correct permissions to chezmoi directory
  file:
    path: ~/.local/share/chezmoi
    mode: 0700

- name: Sync dotfiles
  command: chezmoi apply
