- name: Install shell tools
  aur:
    name:
      - autojump
      - bat
      - chezmoi
      - diff-so-fancy
      - direnv
      - fd
      - fzf
      - htop
      - noti
      - prettyping
      - tldr

- name: Install *very important* shell tools
  aur:
    name:
      - figlet
      - lolcat

- name: Install dev tools
  aur:
    name:
      - git
      - git-lfs
      - gnupg
      - hub
      - nano
      - python-pipenv

- name: Import Dropbox gpg key
  command: gpg --recv-keys 1C61A2656FB57B7E4DE0F4C1FC918B335044912E

- name: Install other software
  aur:
    name:
      - alacritty
      - android-sdk-platform-tools
      - anki
      - beets
      - caffeine-ng
      - calibre
      - cryptomator
      - aur/dropbox
      - emacs
      - enpass-bin
      - firefox
      - ghostwriter
      - gimp
      - gnome-twitch
      - gpodder
      - joplin
      - mps-youtube
      - mpv
      - mypaint
      - nautilus-dropbox
      - ngrok
      - paperwork
      - pick-colour-picker
      - qomui
      - rclone
      - restic
      - sublime-merge
      - todotxt
      - vlc
      - xmind
      - youtube-dl
      - zotero

- name: Set default Java to openjdk-10
  command: sudo archlinux-java set java-10-openjdk
  become: true

- name: Make xmind run correctly with openjdk (1)
  lineinfile:
    backup: true
    line: --add-modules=java.se.ee
    path: /usr/share/xmind/XMind/XMind.ini
    state: absent
  become: true

- name: Make xmind run correctly with openjdk (2)
  lineinfile:
    backup: true
    line: -vm /usr/lib/jvm/java-10-openjdk/bin
    path: /usr/share/xmind/XMind/XMind.ini
    state: present
  become: true

- name: Get nano syntax highlighting files
  git:
    repo: https://github.com/scopatz/nanorc.git
    dest: ~/.nano
