- name: Install shell tools
  aur:
    name:
      - autojump
      - bat
      - chezmoi-bin
      - diff-so-fancy
      - direnv
      - fd
      - fzf
      - htop
      - noti
      - prettyping
      - tldr

- name: Install *very important* shell tools
  aur:
    name:
      - figlet
      - lolcat

- name: Install dev tools
  aur:
    name:
      - git
      - git-lfs
      - gnupg
      - hub
      - nano
      - python-pipenv

- name: Import Dropbox gpg key
  command: gpg --recv-keys 1C61A2656FB57B7E4DE0F4C1FC918B335044912E

- name: Install other software
  aur:
    name:
      - alacritty
      - anki
      - beets
      - caffeine-ng
      - calibre
      - cpod
      - cryptomator
      - aur/dropbox
      - emacs
      - enpass-bin
      - firefox
      - gimp
      - ghostwriter
      - gnome-twitch
      - mps-youtube
      - mpv
      - mypaint
      - nautilus-dropbox
      - ngrok
      - paperwork
      - pick-colour-picker
      - qomui
      - rclone
      - restic
      - sublime-merge
      - todotxt
      - vlc
      - youtube-dl
      - zotero

- name: Get nano syntax highlighting files
  git:
    repo: https://github.com/scopatz/nanorc.git
    dest: ~/.nano
